[package]
name = "tja_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.3"

tja = { version = "0.1.0", path = "../tja" }
glge = { version = "0.1.0", path = "../glge" }